import { RatesApiService } from '@app/rates-api/rates-api.service';
import { HttpException, HttpStatus, Injectable } from '@nestjs/common';
import { ConvertDto } from './dto/convert.dto';

@Injectable()
export class ConvertService {
	constructor(
		private readonly ratesApiService: RatesApiService,
	) {}

	async convertAmount(convertDto: ConvertDto) {
		const rates = await this.ratesApiService.getAllRates(convertDto.currency);

		if (!rates) {
			throw new HttpException('Currency not found', HttpStatus.BAD_REQUEST)
		}

		const convertation = {
			base_currency: convertDto.currency,
			amount: convertDto.amount,
			exchange_rates: {
				USD: rates.conversion_rates.USD * convertDto.amount,
				AED: rates.conversion_rates.AED * convertDto.amount,
				AFN: rates.conversion_rates.AFN * convertDto.amount,
				ALL: rates.conversion_rates.ALL * convertDto.amount,
				AMD: rates.conversion_rates.AMD * convertDto.amount,
				ANG: rates.conversion_rates.ANG * convertDto.amount,
				AOA: rates.conversion_rates.AOA * convertDto.amount,
				ARS: rates.conversion_rates.ARS * convertDto.amount,
				AUD: rates.conversion_rates.AUD * convertDto.amount,
				AWG: rates.conversion_rates.AWG * convertDto.amount,
				AZN: rates.conversion_rates.AZN * convertDto.amount,
				BAM: rates.conversion_rates.BAM * convertDto.amount,
				BBD: rates.conversion_rates.BBD * convertDto.amount,
				BDT: rates.conversion_rates.BDT * convertDto.amount,
				BGN: rates.conversion_rates.BGN * convertDto.amount,
				BHD: rates.conversion_rates.BHD * convertDto.amount,
				BIF: rates.conversion_rates.BIF * convertDto.amount,
				BMD: rates.conversion_rates.BMD * convertDto.amount,
				BND: rates.conversion_rates.BND * convertDto.amount,
				BOB: rates.conversion_rates.BOB * convertDto.amount,
				BRL: rates.conversion_rates.BRL * convertDto.amount,
				BSD: rates.conversion_rates.BSD * convertDto.amount,
				BTN: rates.conversion_rates.BTN * convertDto.amount,
				BWP: rates.conversion_rates.BWP * convertDto.amount,
				BYN: rates.conversion_rates.BYN * convertDto.amount,
				BZD: rates.conversion_rates.BZD * convertDto.amount,
				CAD: rates.conversion_rates.CAD * convertDto.amount,
				CDF: rates.conversion_rates.CDF * convertDto.amount,
				CHF: rates.conversion_rates.CHF * convertDto.amount,
				CLP: rates.conversion_rates.CLP * convertDto.amount,
				CNY: rates.conversion_rates.CNY * convertDto.amount,
				COP: rates.conversion_rates.COP * convertDto.amount,
				CRC: rates.conversion_rates.CRC * convertDto.amount,
				CUP: rates.conversion_rates.CUP * convertDto.amount,
				CVE: rates.conversion_rates.CVE * convertDto.amount,
				CZK: rates.conversion_rates.CZK * convertDto.amount,
				DJF: rates.conversion_rates.DJF * convertDto.amount,
				DKK: rates.conversion_rates.DKK * convertDto.amount,
				DOP: rates.conversion_rates.DOP * convertDto.amount,
				DZD: rates.conversion_rates.DZD * convertDto.amount,
				EGP: rates.conversion_rates.EGP * convertDto.amount,
				ERN: rates.conversion_rates.ERN * convertDto.amount,
				ETB: rates.conversion_rates.ETB * convertDto.amount,
				EUR: rates.conversion_rates.EUR * convertDto.amount,
				FJD: rates.conversion_rates.FJD * convertDto.amount,
				FKP: rates.conversion_rates.FKP * convertDto.amount,
				FOK: rates.conversion_rates.FOK * convertDto.amount,
				GBP: rates.conversion_rates.GBP * convertDto.amount,
				GEL: rates.conversion_rates.GEL * convertDto.amount,
				GGP: rates.conversion_rates.GGP * convertDto.amount,
				GHS: rates.conversion_rates.GHS * convertDto.amount,
				GIP: rates.conversion_rates.GIP * convertDto.amount,
				GMD: rates.conversion_rates.GMD * convertDto.amount,
				GNF: rates.conversion_rates.GNF * convertDto.amount,
				GTQ: rates.conversion_rates.GTQ * convertDto.amount,
				GYD: rates.conversion_rates.GYD * convertDto.amount,
				HKD: rates.conversion_rates.HKD * convertDto.amount,
				HNL: rates.conversion_rates.HNL * convertDto.amount,
				HRK: rates.conversion_rates.HRK * convertDto.amount,
				HTG: rates.conversion_rates.HTG * convertDto.amount,
				HUF: rates.conversion_rates.HUF * convertDto.amount,
				IDR: rates.conversion_rates.IDR * convertDto.amount,
				ILS: rates.conversion_rates.ILS * convertDto.amount,
				IMP: rates.conversion_rates.IMP * convertDto.amount,
				INR: rates.conversion_rates.INR * convertDto.amount,
				IQD: rates.conversion_rates.IQD * convertDto.amount,
				IRR: rates.conversion_rates.IRR * convertDto.amount,
				ISK: rates.conversion_rates.ISK * convertDto.amount,
				JEP: rates.conversion_rates.JEP * convertDto.amount,
				JMD: rates.conversion_rates.JMD * convertDto.amount,
				JOD: rates.conversion_rates.JOD * convertDto.amount,
				JPY: rates.conversion_rates.JPY * convertDto.amount,
				KES: rates.conversion_rates.KES * convertDto.amount,
				KGS: rates.conversion_rates.KGS * convertDto.amount,
				KHR: rates.conversion_rates.KHR * convertDto.amount,
				KID: rates.conversion_rates.KID * convertDto.amount,
				KMF: rates.conversion_rates.KMF * convertDto.amount,
				KRW: rates.conversion_rates.KRW * convertDto.amount,
				KWD: rates.conversion_rates.KWD * convertDto.amount,
				KYD: rates.conversion_rates.KYD * convertDto.amount,
				KZT: rates.conversion_rates.KZT * convertDto.amount,
				LAK: rates.conversion_rates.LAK * convertDto.amount,
				LBP: rates.conversion_rates.LBP * convertDto.amount,
				LKR: rates.conversion_rates.LKR * convertDto.amount,
				LRD: rates.conversion_rates.LRD * convertDto.amount,
				LSL: rates.conversion_rates.LSL * convertDto.amount,
				LYD: rates.conversion_rates.LYD * convertDto.amount,
				MAD: rates.conversion_rates.MAD * convertDto.amount,
				MDL: rates.conversion_rates.MDL * convertDto.amount,
				MGA: rates.conversion_rates.MGA * convertDto.amount,
				MKD: rates.conversion_rates.MKD * convertDto.amount,
				MMK: rates.conversion_rates.MMK * convertDto.amount,
				MNT: rates.conversion_rates.MNT * convertDto.amount,
				MOP: rates.conversion_rates.MOP * convertDto.amount,
				MRU: rates.conversion_rates.MRU * convertDto.amount,
				MUR: rates.conversion_rates.MUR * convertDto.amount,
				MVR: rates.conversion_rates.MVR * convertDto.amount,
				MWK: rates.conversion_rates.MWK * convertDto.amount,
				MXN: rates.conversion_rates.MXN * convertDto.amount,
				MYR: rates.conversion_rates.MYR * convertDto.amount,
				MZN: rates.conversion_rates.MZN * convertDto.amount,
				NAD: rates.conversion_rates.NAD * convertDto.amount,
				NGN: rates.conversion_rates.NGN * convertDto.amount,
				NIO: rates.conversion_rates.NIO * convertDto.amount,
				NOK: rates.conversion_rates.NOK * convertDto.amount,
				NPR: rates.conversion_rates.NPR * convertDto.amount,
				NZD: rates.conversion_rates.NZD * convertDto.amount,
				OMR: rates.conversion_rates.OMR * convertDto.amount,
				PAB: rates.conversion_rates.PAB * convertDto.amount,
				PEN: rates.conversion_rates.PEN * convertDto.amount,
				PGK: rates.conversion_rates.PGK * convertDto.amount,
				PHP: rates.conversion_rates.PHP * convertDto.amount,
				PKR: rates.conversion_rates.PKR * convertDto.amount,
				PLN: rates.conversion_rates.PLN * convertDto.amount,
				PYG: rates.conversion_rates.PYG * convertDto.amount,
				QAR: rates.conversion_rates.QAR * convertDto.amount,
				RON: rates.conversion_rates.RON * convertDto.amount,
				RSD: rates.conversion_rates.RSD * convertDto.amount,
				RUB: rates.conversion_rates.RUB * convertDto.amount,
				RWF: rates.conversion_rates.RWF * convertDto.amount,
				SAR: rates.conversion_rates.SAR * convertDto.amount,
				SBD: rates.conversion_rates.SBD * convertDto.amount,
				SCR: rates.conversion_rates.SCR * convertDto.amount,
				SDG: rates.conversion_rates.SDG * convertDto.amount,
				SEK: rates.conversion_rates.SEK * convertDto.amount,
				SGD: rates.conversion_rates.SGD * convertDto.amount,
				SHP: rates.conversion_rates.SHP * convertDto.amount,
				SLL: rates.conversion_rates.SLL * convertDto.amount,
				SOS: rates.conversion_rates.SOS * convertDto.amount,
				SRD: rates.conversion_rates.SRD * convertDto.amount,
				SSP: rates.conversion_rates.SSP * convertDto.amount,
				STN: rates.conversion_rates.STN * convertDto.amount,
				SYP: rates.conversion_rates.SYP * convertDto.amount,
				SZL: rates.conversion_rates.SZL * convertDto.amount,
				THB: rates.conversion_rates.THB * convertDto.amount,
				TJS: rates.conversion_rates.TJS * convertDto.amount,
				TMT: rates.conversion_rates.TMT * convertDto.amount,
				TND: rates.conversion_rates.TND * convertDto.amount,
				TOP: rates.conversion_rates.TOP * convertDto.amount,
				TRY: rates.conversion_rates.TRY * convertDto.amount,
				TTD: rates.conversion_rates.TTD * convertDto.amount,
				TVD: rates.conversion_rates.TVD * convertDto.amount,
				TWD: rates.conversion_rates.TWD * convertDto.amount,
				TZS: rates.conversion_rates.TZS * convertDto.amount,
				UAH: rates.conversion_rates.UAH * convertDto.amount,
				UGX: rates.conversion_rates.UGX * convertDto.amount,
				UYU: rates.conversion_rates.UYU * convertDto.amount,
				UZS: rates.conversion_rates.UZS * convertDto.amount,
				VES: rates.conversion_rates.VES * convertDto.amount,
				VND: rates.conversion_rates.VND * convertDto.amount,
				VUV: rates.conversion_rates.VUV * convertDto.amount,
				WST: rates.conversion_rates.WST * convertDto.amount,
				XAF: rates.conversion_rates.XAF * convertDto.amount,
				XCD: rates.conversion_rates.XCD * convertDto.amount,
				XDR: rates.conversion_rates.XDR * convertDto.amount,
				XOF: rates.conversion_rates.XOF * convertDto.amount,
				XPF: rates.conversion_rates.XPF * convertDto.amount,
				YER: rates.conversion_rates.YER * convertDto.amount,
				ZAR: rates.conversion_rates.ZAR * convertDto.amount,
				ZMW: rates.conversion_rates.ZMW * convertDto.amount,
				ZWL: rates.conversion_rates.ZWL * convertDto.amount,
			}
		}

		return convertation;
	}

}
